/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import myprojects.spellingchecker.SpellCheck;

/**
 *
 * @author mitch
 */
public class FrameSpellChecker extends javax.swing.JFrame {

    /**
     * Creates new form FrameSpellChecker
     */
    DefaultListModel<String> listModel;
    
    public FrameSpellChecker() {
        initComponents();
        //btnAddToDictionary.setVisible(false);
        //btnCleanWorkSheet.setVisible(false);
        listModel = new DefaultListModel<>();
        lstMisspelledWords.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPane = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btncheckSpelling = new javax.swing.JButton();
        btnCleanWorkSheet = new javax.swing.JButton();
        btnAddToDictionary = new javax.swing.JButton();
        btnCheckDictionary = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMisspelledWords = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spell checker");

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jScrollPane1.setViewportView(txtPane);

        jLabel1.setText(" Please, write tyour text here...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btncheckSpelling.setText("Check spelling");
        btncheckSpelling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckSpellingActionPerformed(evt);
            }
        });

        btnCleanWorkSheet.setText("Clean worksheet");
        btnCleanWorkSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanWorkSheetActionPerformed(evt);
            }
        });

        btnAddToDictionary.setText("Add to dictionary");
        btnAddToDictionary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToDictionaryActionPerformed(evt);
            }
        });

        btnCheckDictionary.setText("Check dictionary");
        btnCheckDictionary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckDictionaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btncheckSpelling)
                .addGap(117, 117, 117)
                .addComponent(btnCleanWorkSheet)
                .addGap(67, 67, 67)
                .addComponent(btnAddToDictionary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCheckDictionary)
                .addGap(50, 50, 50))
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncheckSpelling)
                    .addComponent(btnCleanWorkSheet)
                    .addComponent(btnAddToDictionary)
                    .addComponent(btnCheckDictionary))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Misspelled words"));

        lstMisspelledWords.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(lstMisspelledWords);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCleanWorkSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanWorkSheetActionPerformed
        txtPane.setText("");
        listModel.clear();
        
    }//GEN-LAST:event_btnCleanWorkSheetActionPerformed

    private void btncheckSpellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckSpellingActionPerformed
        // TODO add your handling code here:
       
        String texto = txtPane.getText();
        System.out.println(texto);
        int s = texto.length();
        
        File file = new File("C:\\Users\\mitch\\OneDrive\\Documentos\\NetBeansProjects\\232CC232Project\\src\\main\\java\\uni\\aed\\spellChecker\\test.txt");
        FileOutputStream fo = null;
        try {
            fo = new FileOutputStream(file);
            for(int i = 0; i < s; i++)
                fo.write(texto.charAt(i));
              
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error with test.txt file");
        } finally {
            try {
                fo.close();
            } catch (IOException e) {
                System.out.println("Error al cerrar el archivo test.txt");
            }
        }
        
        ArrayList<String> misspelledWords = new ArrayList<>();
        SpellCheck sc = new SpellCheck();
        misspelledWords = sc.checkSpelling();
        listModel.clear();
        listModel.addAll(misspelledWords);
        for(String str : misspelledWords)
           System.out.println(str);
            
    }//GEN-LAST:event_btncheckSpellingActionPerformed

    
    private void btnAddToDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToDictionaryActionPerformed

        // yes = 0
        String newWord = txtPane.getSelectedText();
        System.out.println(newWord);
        int option = JOptionPane.showConfirmDialog(rootPane, "Do you want to add \""
            + newWord + "\" to the  dictionary?", "Add word", JOptionPane.YES_NO_CANCEL_OPTION);

        if (option == 0){
            SpellCheck sc = new SpellCheck();
            sc.addToDictionary(newWord);
        }
    }//GEN-LAST:event_btnAddToDictionaryActionPerformed

    private void btnCheckDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckDictionaryActionPerformed
        
        SpellCheck sc = new SpellCheck();
        sc.checkDictionary();
        
        FrameDictionary fr = new FrameDictionary();
        fr.setLocationRelativeTo(null);
        fr.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnCheckDictionaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSpellChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSpellChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSpellChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSpellChecker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSpellChecker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToDictionary;
    private javax.swing.JButton btnCheckDictionary;
    private javax.swing.JButton btnCleanWorkSheet;
    private javax.swing.JButton btncheckSpelling;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstMisspelledWords;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JTextPane txtPane;
    // End of variables declaration//GEN-END:variables
}
